const mongoose = require('mongoose');
require('dotenv').config({ path: '.env.local' });

// MongoDB connection
const MONGODB_URI = process.env.MONGODB_URI;
if (!MONGODB_URI) {
  console.error("MONGODB_URI environment variable is not defined in .env.local");
  process.exit(1);
}

mongoose.connect(MONGODB_URI)
  .then(() => console.log('Connected to MongoDB'))
  .catch(err => {
    console.error('Failed to connect to MongoDB:', err);
    process.exit(1);
  });

// Define product schema directly in this script
const ProductSchema = new mongoose.Schema({
  title: { type: String, required: true },
  category: { type: String, required: true },
  image: { type: String, required: true },
  rating: { type: Number, default: 0 },
  reviewCount: { type: Number, default: 0 },
  description: { type: String, required: true },
  price: { type: String, required: true },
  features: { type: [String], default: [] },
  details: {
    type: [
      {
        label: { type: String },
        value: { type: String },
      },
    ],
    default: [],
  },
  variants: { type: Array, default: [] },
  longDescription: { type: String, required: true },
});

// Create the model (if already defined, use the existing one)
const Product = mongoose.models.Product || mongoose.model('Product', ProductSchema);

const products = [
  // ========================
  // --- Beauty Products ---
  // ========================
  {
    title: "Advanced Night Repair Serum",
    category: "Beauty",
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 352,
    description: "Advanced Night Repair Synchronized Multi-Recovery Complex. Reduces multiple signs of aging.",
    price: "$75.00",
    features: [
      "Patented synchronization technology",
      "Reduces fine lines and wrinkles",
      "Improves radiance",
      "Strengthens skin barrier",
      "Oil-free formula",
    ],
    details: [
      { label: "Size", value: "30ml" },
      { label: "Item Form", value: "Serum" },
      { label: "Skin Type", value: "All Skin Types" },
      { label: "Brand", value: "Estée Lauder" },
    ],
    variants: [
      { id: 101, size: "30ml", price: "$75.00" },
      { id: 102, size: "50ml", price: "$105.00" },
      { id: 103, size: "100ml", price: "$185.00" },
    ],
    longDescription: "Advanced Night Repair Synchronized Multi-Recovery Complex is a revolutionary anti-aging serum that dramatically reduces lines and wrinkles while boosting skin radiance.",
  },
  {
    title: "Radiant Glow Moisturizer",
    category: "Beauty",
    image: "https://via.placeholder.com/800x600?text=Radiant+Glow+Moisturizer",
    rating: 4.5,
    reviewCount: 210,
    description: "A lightweight moisturizer that hydrates and enhances your natural glow.",
    price: "$45.00",
    features: [
      "Hydrating formula",
      "Lightweight texture",
      "Non-greasy finish",
    ],
    details: [
      { label: "Size", value: "50ml" },
      { label: "Skin Type", value: "Normal to Dry" },
    ],
    variants: [],
    longDescription: "Radiant Glow Moisturizer is designed for daily use to provide long-lasting hydration and a luminous finish for all skin types.",
  },
  {
    title: "Hydrating Facial Cleanser",
    category: "Beauty",
    image: "https://via.placeholder.com/800x600?text=Hydrating+Facial+Cleanser",
    rating: 4.6,
    reviewCount: 180,
    description: "Gentle cleanser that removes impurities while retaining moisture.",
    price: "$30.00",
    features: [
      "Gentle formula",
      "Suitable for sensitive skin",
      "Non-drying",
    ],
    details: [
      { label: "Volume", value: "150ml" },
      { label: "Type", value: "Foaming Cleanser" },
    ],
    variants: [],
    longDescription: "This Hydrating Facial Cleanser ensures clean and refreshed skin without stripping away natural oils.",
  },
  {
    title: "Rejuvenating Eye Cream",
    category: "Beauty",
    image: "https://via.placeholder.com/800x600?text=Rejuvenating+Eye+Cream",
    rating: 4.7,
    reviewCount: 240,
    description: "Targeted eye cream that reduces puffiness and dark circles.",
    price: "$55.00",
    features: [
      "Reduces puffiness",
      "Minimizes dark circles",
      "Lightweight formula",
    ],
    details: [
      { label: "Size", value: "15ml" },
      { label: "Usage", value: "Daily" },
    ],
    variants: [],
    longDescription: "Rejuvenating Eye Cream brightens and smooths the delicate eye area for a refreshed look.",
  },
  {
    title: "Matte Lipstick Collection",
    category: "Beauty",
    image: "https://via.placeholder.com/800x600?text=Matte+Lipstick+Collection",
    rating: 4.4,
    reviewCount: 300,
    description: "A collection of long-lasting matte lipsticks in various shades.",
    price: "$35.00",
    features: [
      "Long-lasting",
      "Vibrant colors",
      "Smooth application",
    ],
    details: [
      { label: "Set", value: "5 shades" },
    ],
    variants: [],
    longDescription: "Our Matte Lipstick Collection delivers bold, beautiful color that lasts all day.",
  },
  {
    title: "Volumizing Mascara",
    category: "Beauty",
    image: "https://via.placeholder.com/800x600?text=Volumizing+Mascara",
    rating: 4.5,
    reviewCount: 275,
    description: "Mascara that adds volume and length for striking lashes.",
    price: "$28.00",
    features: [
      "Volume boosting",
      "Lengthening fibers",
      "Smudge-proof",
    ],
    details: [
      { label: "Size", value: "10ml" },
    ],
    variants: [],
    longDescription: "Volumizing Mascara provides fuller, longer lashes without clumping.",
  },
  {
    title: "Age-Defying Foundation",
    category: "Beauty",
    image: "https://via.placeholder.com/800x600?text=Age-Defying+Foundation",
    rating: 4.3,
    reviewCount: 190,
    description: "Foundation that provides coverage while reducing signs of aging.",
    price: "$50.00",
    features: [
      "Lightweight",
      "Anti-aging ingredients",
      "Buildable coverage",
    ],
    details: [
      { label: "Shade Range", value: "10 shades" },
    ],
    variants: [],
    longDescription: "Our Age-Defying Foundation blends seamlessly for a natural look and nourishes your skin with every application.",
  },
  {
    title: "Nourishing Hair Serum",
    category: "Beauty",
    image: "https://via.placeholder.com/800x600?text=Nourishing+Hair+Serum",
    rating: 4.6,
    reviewCount: 220,
    description: "Hair serum that adds shine and reduces frizz.",
    price: "$40.00",
    features: [
      "Adds shine",
      "Reduces frizz",
      "Non-greasy formula",
    ],
    details: [
      { label: "Volume", value: "50ml" },
    ],
    variants: [],
    longDescription: "Nourishing Hair Serum delivers essential nutrients for smoother, silkier hair.",
  },
  {
    title: "Detoxifying Face Mask",
    category: "Beauty",
    image: "https://via.placeholder.com/800x600?text=Detoxifying+Face+Mask",
    rating: 4.7,
    reviewCount: 260,
    description: "Face mask that detoxifies and clarifies the skin.",
    price: "$25.00",
    features: [
      "Detoxifies",
      "Deep cleansing",
      "Revitalizes skin",
    ],
    details: [
      { label: "Pack Size", value: "1 mask" },
    ],
    variants: [],
    longDescription: "Our Detoxifying Face Mask purifies the skin, removing impurities and promoting a clear complexion.",
  },
  {
    title: "Brightening Vitamin C Serum",
    category: "Beauty",
    image: "https://via.placeholder.com/800x600?text=Brightening+Vitamin+C+Serum",
    rating: 4.8,
    reviewCount: 310,
    description: "Vitamin C serum that brightens skin tone and reduces hyperpigmentation.",
    price: "$65.00",
    features: [
      "Brightens skin",
      "Reduces dark spots",
      "Antioxidant-rich",
    ],
    details: [
      { label: "Size", value: "30ml" },
    ],
    variants: [],
    longDescription: "Brightening Vitamin C Serum evens skin tone and enhances radiance for a youthful glow.",
  },

  // ====================
  // --- Cars Products ---
  // ====================
  {
    title: "2023 Luxury Sedan",
    category: "Cars",
    image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    rating: 4.6,
    reviewCount: 290,
    description: "Experience luxury and performance with our 2023 Luxury Sedan featuring advanced technology and superior comfort.",
    price: "$45,000.00",
    features: [
      "Sleek design",
      "Advanced safety features",
      "High fuel efficiency",
      "Premium interior materials",
    ],
    details: [
      { label: "Engine", value: "V6" },
      { label: "Transmission", value: "Automatic" },
      { label: "Fuel Type", value: "Gasoline" },
      { label: "Color", value: "Metallic Silver" },
    ],
    variants: [],
    longDescription: "Our 2023 Luxury Sedan offers an exquisite blend of performance, comfort, and state-of-the-art technology.",
  },
  {
    title: "Sporty Coupe 2023",
    category: "Cars",
    image: "https://via.placeholder.com/800x600?text=Sporty+Coupe+2023",
    rating: 4.7,
    reviewCount: 310,
    description: "A dynamic and stylish coupe that combines speed with luxury.",
    price: "$55,000.00",
    features: [
      "Sporty design",
      "High performance",
      "Responsive handling",
    ],
    details: [
      { label: "Engine", value: "V8" },
      { label: "Transmission", value: "Manual" },
    ],
    variants: [],
    longDescription: "Sporty Coupe 2023 is engineered for those who crave performance and style on every drive.",
  },
  {
    title: "Eco-Friendly Hybrid",
    category: "Cars",
    image: "https://via.placeholder.com/800x600?text=Eco-Friendly+Hybrid",
    rating: 4.5,
    reviewCount: 250,
    description: "A hybrid vehicle offering impressive efficiency without compromising performance.",
    price: "$35,000.00",
    features: [
      "Fuel efficient",
      "Low emissions",
      "Innovative technology",
    ],
    details: [
      { label: "Engine", value: "Hybrid" },
      { label: "Fuel Economy", value: "50 MPG" },
    ],
    variants: [],
    longDescription: "Eco-Friendly Hybrid combines modern innovation with exceptional fuel efficiency for the conscious driver.",
  },
  {
    title: "Compact City Car",
    category: "Cars",
    image: "https://via.placeholder.com/800x600?text=Compact+City+Car",
    rating: 4.4,
    reviewCount: 220,
    description: "A perfectly sized car for urban driving, offering ease of parking and excellent fuel efficiency.",
    price: "$20,000.00",
    features: [
      "Compact design",
      "Easy parking",
      "Efficient",
    ],
    details: [
      { label: "Engine", value: "I4" },
      { label: "Fuel Economy", value: "35 MPG" },
    ],
    variants: [],
    longDescription: "The Compact City Car is ideal for urban lifestyles, combining agility with practicality for daily commutes.",
  },
  {
    title: "Rugged Off-Road SUV",
    category: "Cars",
    image: "https://via.placeholder.com/800x600?text=Rugged+Off-Road+SUV",
    rating: 4.8,
    reviewCount: 330,
    description: "Built for adventure, this SUV excels on challenging terrains while providing superior comfort.",
    price: "$60,000.00",
    features: [
      "All-wheel drive",
      "Robust suspension",
      "Off-road capabilities",
    ],
    details: [
      { label: "Engine", value: "V6" },
      { label: "Transmission", value: "Automatic" },
    ],
    variants: [],
    longDescription: "Rugged Off-Road SUV is engineered to conquer the toughest landscapes while ensuring a smooth ride.",
  },
  {
    title: "Electric Future Model",
    category: "Cars",
    image: "https://via.placeholder.com/800x600?text=Electric+Future+Model",
    rating: 4.9,
    reviewCount: 400,
    description: "A state-of-the-art electric car that epitomizes innovation and sustainable driving.",
    price: "$70,000.00",
    features: [
      "Electric powertrain",
      "Zero emissions",
      "Futuristic design",
    ],
    details: [
      { label: "Battery Range", value: "300 miles" },
      { label: "Charging Time", value: "1 hour (fast charge)" },
    ],
    variants: [],
    longDescription: "Electric Future Model redefines automotive technology with its efficient electric engine and modern design.",
  },
  {
    title: "Vintage Classic Car",
    category: "Cars",
    image: "https://via.placeholder.com/800x600?text=Vintage+Classic+Car",
    rating: 4.3,
    reviewCount: 180,
    description: "A timeless classic car that brings the charm of yesteryear to modern roads.",
    price: "$80,000.00",
    features: [
      "Classic design",
      "Restored interior",
      "Collector's item",
    ],
    details: [
      { label: "Year", value: "1965" },
      { label: "Mileage", value: "80,000 miles" },
    ],
    variants: [],
    longDescription: "Vintage Classic Car offers a unique blend of nostalgia and performance, ideal for collectors and enthusiasts alike.",
  },
  {
    title: "High-Performance Sports Car",
    category: "Cars",
    image: "https://via.placeholder.com/800x600?text=High-Performance+Sports+Car",
    rating: 4.9,
    reviewCount: 350,
    description: "Experience the thrill of speed with our high-performance sports car, engineered for precision.",
    price: "$90,000.00",
    features: [
      "Rapid acceleration",
      "Precision handling",
      "Aerodynamic design",
    ],
    details: [
      { label: "Engine", value: "V8" },
      { label: "0-60 mph", value: "3.5 seconds" },
    ],
    variants: [],
    longDescription: "High-Performance Sports Car is designed for adrenaline junkies who crave both speed and luxury.",
  },

  // ==========================
  // --- Electronics Products ---
  // ==========================
  {
    title: "Pro Display XDR Monitor",
    category: "Electronics",
    image: "https://images.unsplash.com/photo-1616763355548-1b606f439f86?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    rating: 4.9,
    reviewCount: 127,
    description: "A professional display with Retina 6K resolution, incredible HDR performance, and outstanding color accuracy.",
    price: "$4,999.00",
    features: [
      "6K Retina display",
      "HDR support",
      "Professional-grade color accuracy",
    ],
    details: [
      { label: "Screen Size", value: "32 inches" },
      { label: "Resolution", value: "6016 x 3384" },
      { label: "Connectivity", value: "Thunderbolt 3" },
    ],
    variants: [],
    longDescription: "Experience stunning visuals and exceptional performance with the Pro Display XDR Monitor, ideal for creative professionals.",
  },
  {
    title: "Ultra HD Smart TV",
    category: "Electronics",
    image: "https://via.placeholder.com/800x600?text=Ultra+HD+Smart+TV",
    rating: 4.7,
    reviewCount: 200,
    description: "A 55-inch Ultra HD Smart TV with seamless streaming and immersive visuals.",
    price: "$1,299.00",
    features: [
      "4K Ultra HD",
      "Smart connectivity",
      "Built-in streaming apps",
    ],
    details: [
      { label: "Screen Size", value: "55 inches" },
      { label: "Resolution", value: "3840 x 2160" },
    ],
    variants: [],
    longDescription: "Ultra HD Smart TV provides an immersive viewing experience with brilliant color and clarity.",
  },
  {
    title: "Noise Cancelling Headphones",
    category: "Electronics",
    image: "https://via.placeholder.com/800x600?text=Noise+Cancelling+Headphones",
    rating: 4.8,
    reviewCount: 320,
    description: "Premium noise cancelling headphones that block out distractions for an immersive audio experience.",
    price: "$299.00",
    features: [
      "Active noise cancellation",
      "Wireless connectivity",
      "Comfortable design",
    ],
    details: [
      { label: "Battery Life", value: "30 hours" },
    ],
    variants: [],
    longDescription: "Experience pure sound and minimal distractions with our Noise Cancelling Headphones, perfect for travel and work.",
  },
  {
    title: "Wireless Bluetooth Speaker",
    category: "Electronics",
    image: "https://via.placeholder.com/800x600?text=Wireless+Bluetooth+Speaker",
    rating: 4.6,
    reviewCount: 250,
    description: "Portable Bluetooth speaker delivering powerful sound and extended battery life.",
    price: "$150.00",
    features: [
      "Portable design",
      "High-quality audio",
      "Long battery life",
    ],
    details: [
      { label: "Battery Life", value: "20 hours" },
    ],
    variants: [],
    longDescription: "The Wireless Bluetooth Speaker is your go-to device for on-the-go music and entertainment.",
  },
  {
    title: "Gaming Laptop Pro",
    category: "Electronics",
    image: "https://via.placeholder.com/800x600?text=Gaming+Laptop+Pro",
    rating: 4.9,
    reviewCount: 450,
    description: "A high-performance gaming laptop designed to deliver an immersive gaming experience.",
    price: "$2,299.00",
    features: [
      "Powerful GPU",
      "High refresh rate display",
      "RGB backlit keyboard",
    ],
    details: [
      { label: "Processor", value: "Intel i7" },
      { label: "RAM", value: "16GB" },
    ],
    variants: [],
    longDescription: "Gaming Laptop Pro is built to handle the latest titles with ease, offering superior performance and visuals.",
  },
  {
    title: "Smart Home Assistant",
    category: "Electronics",
    image: "https://via.placeholder.com/800x600?text=Smart+Home+Assistant",
    rating: 4.5,
    reviewCount: 180,
    description: "Voice-activated home assistant to control your smart devices effortlessly.",
    price: "$99.00",
    features: [
      "Voice control",
      "Smart home integration",
      "Compact design",
    ],
    details: [
      { label: "Compatibility", value: "iOS & Android" },
    ],
    variants: [],
    longDescription: "Smart Home Assistant makes managing your connected devices simple with intuitive voice commands.",
  },
  {
    title: "Advanced DSLR Camera",
    category: "Electronics",
    image: "https://via.placeholder.com/800x600?text=Advanced+DSLR+Camera",
    rating: 4.8,
    reviewCount: 210,
    description: "Capture stunning photos with this advanced DSLR camera featuring high resolution and fast autofocus.",
    price: "$1,899.00",
    features: [
      "High resolution",
      "Fast autofocus",
      "Interchangeable lenses",
    ],
    details: [
      { label: "Sensor", value: "24MP" },
      { label: "ISO Range", value: "100-25600" },
    ],
    variants: [],
    longDescription: "Advanced DSLR Camera is the perfect tool for professional photographers who demand excellence in image quality.",
  },
  {
    title: "Portable Projector",
    category: "Electronics",
    image: "https://via.placeholder.com/800x600?text=Portable+Projector",
    rating: 4.4,
    reviewCount: 150,
    description: "A compact and portable projector ideal for home entertainment and presentations.",
    price: "$350.00",
    features: [
      "Compact design",
      "HD projection",
      "Easy setup",
    ],
    details: [
      { label: "Resolution", value: "1080p" },
    ],
    variants: [],
    longDescription: "Portable Projector offers versatility for both professional and home use, delivering clear and vibrant images.",
  },

  // ===============================
  // --- Home & Garden Products ---
  // ===============================
  {
    title: "Luxury Down Comforter",
    category: "Home & Garden",
    image: "https://images.unsplash.com/photo-1613977257363-707ba9348227?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 208,
    description: "Premium all-season down comforter with a cotton shell for maximum loft and warmth.",
    price: "$199.00",
    features: [
      "Premium down fill",
      "Cotton shell",
      "All-season comfort",
    ],
    details: [
      { label: "Size", value: "Queen" },
      { label: "Material", value: "Down & Cotton" },
    ],
    variants: [],
    longDescription: "Stay warm and stylish with our Luxury Down Comforter designed to provide optimal comfort all year round.",
  },
  {
    title: "Modern Sofa Set",
    category: "Home & Garden",
    image: "https://via.placeholder.com/800x600?text=Modern+Sofa+Set",
    rating: 4.5,
    reviewCount: 175,
    description: "A comfortable and stylish sofa set that elevates your living room.",
    price: "$899.00",
    features: [
      "Ergonomic design",
      "High-quality fabric",
      "Sturdy construction",
    ],
    details: [
      { label: "Material", value: "Fabric" },
      { label: "Seating", value: "3+2" },
    ],
    variants: [],
    longDescription: "Modern Sofa Set combines style with comfort, making it the perfect centerpiece for your living area.",
  },
  {
    title: "Elegant Dining Table",
    category: "Home & Garden",
    image: "https://via.placeholder.com/800x600?text=Elegant+Dining+Table",
    rating: 4.6,
    reviewCount: 190,
    description: "A beautifully crafted dining table that brings elegance to your home.",
    price: "$650.00",
    features: [
      "Elegant design",
      "Durable material",
      "Spacious",
    ],
    details: [
      { label: "Dimensions", value: "200x100cm" },
    ],
    variants: [],
    longDescription: "Elegant Dining Table is ideal for family gatherings and special occasions, blending functionality with style.",
  },
  {
    title: "Smart LED Lighting Kit",
    category: "Home & Garden",
    image: "https://via.placeholder.com/800x600?text=Smart+LED+Lighting+Kit",
    rating: 4.7,
    reviewCount: 205,
    description: "Illuminate your home with this smart LED lighting kit featuring customizable colors and brightness.",
    price: "$120.00",
    features: [
      "Smart control",
      "Energy efficient",
      "Customizable settings",
    ],
    details: [
      { label: "Pieces", value: "4 bulbs + hub" },
    ],
    variants: [],
    longDescription: "Smart LED Lighting Kit allows you to set the perfect ambiance in any room with flexible lighting options.",
  },
  {
    title: "Decorative Area Rug",
    category: "Home & Garden",
    image: "https://via.placeholder.com/800x600?text=Decorative+Area+Rug",
    rating: 4.5,
    reviewCount: 160,
    description: "Enhance your living space with this stylish decorative area rug.",
    price: "$150.00",
    features: [
      "Modern design",
      "Soft texture",
      "Easy to clean",
    ],
    details: [
      { label: "Size", value: "5x7 ft" },
    ],
    variants: [],
    longDescription: "Decorative Area Rug adds both style and comfort to any room, making it a versatile home accessory.",
  },
  {
    title: "Indoor Plant Collection",
    category: "Home & Garden",
    image: "https://via.placeholder.com/800x600?text=Indoor+Plant+Collection",
    rating: 4.8,
    reviewCount: 230,
    description: "A curated collection of indoor plants to bring freshness and life to your home.",
    price: "$80.00",
    features: [
      "Air purifying",
      "Low maintenance",
      "Aesthetic appeal",
    ],
    details: [
      { label: "Includes", value: "5 plants" },
    ],
    variants: [],
    longDescription: "Indoor Plant Collection enhances your living space with natural beauty and improved air quality.",
  },
  {
    title: "Outdoor Patio Set",
    category: "Home & Garden",
    image: "https://via.placeholder.com/800x600?text=Outdoor+Patio+Set",
    rating: 4.6,
    reviewCount: 190,
    description: "Upgrade your outdoor space with this comfortable and stylish patio set.",
    price: "$1,200.00",
    features: [
      "Weather resistant",
      "Comfortable seating",
      "Modern design",
    ],
    details: [
      { label: "Pieces", value: "4" },
    ],
    variants: [],
    longDescription: "Outdoor Patio Set is perfect for hosting gatherings or enjoying quiet evenings outdoors.",
  },
  {
    title: "Minimalist Bookshelf",
    category: "Home & Garden",
    image: "https://via.placeholder.com/800x600?text=Minimalist+Bookshelf",
    rating: 4.4,
    reviewCount: 140,
    description: "A sleek and modern bookshelf that complements any decor.",
    price: "$220.00",
    features: [
      "Minimalist design",
      "Sturdy construction",
      "Easy assembly",
    ],
    details: [
      { label: "Material", value: "Wood" },
    ],
    variants: [],
    longDescription: "Minimalist Bookshelf offers a stylish storage solution for books and decorative items in modern homes.",
  },

  // ========================
  // --- Fashion Products ---
  // ========================
  {
    title: "Elegant Evening Gown",
    category: "Fashion",
    image: "https://images.unsplash.com/photo-1542060744-1b2f09a08d72?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    rating: 4.5,
    reviewCount: 154,
    description: "An elegant evening gown that combines modern design with classic elegance.",
    price: "$250.00",
    features: [
      "Luxurious fabric",
      "Intricate detailing",
      "Flattering silhouette",
    ],
    details: [
      { label: "Size", value: "M" },
      { label: "Color", value: "Red" },
      { label: "Material", value: "Silk" },
      { label: "Brand", value: "Fashionista" },
    ],
    variants: [
      { id: 201, size: "S", price: "$230.00" },
      { id: 202, size: "M", price: "$250.00" },
      { id: 203, size: "L", price: "$270.00" },
    ],
    longDescription: "This elegant evening gown is perfect for formal events, offering a timeless style with luxurious silk and intricate details.",
  },
  {
    title: "Casual Summer Dress",
    category: "Fashion",
    image: "https://via.placeholder.com/800x600?text=Casual+Summer+Dress",
    rating: 4.6,
    reviewCount: 200,
    description: "A light and breezy summer dress perfect for everyday wear.",
    price: "$80.00",
    features: [
      "Lightweight",
      "Comfortable fit",
      "Vibrant colors",
    ],
    details: [
      { label: "Size", value: "S-XL" },
      { label: "Material", value: "Cotton" },
    ],
    variants: [],
    longDescription: "Casual Summer Dress is designed to keep you cool and stylish during warm weather with its comfortable and flattering design.",
  },
  {
    title: "Designer Handbag",
    category: "Fashion",
    image: "https://via.placeholder.com/800x600?text=Designer+Handbag",
    rating: 4.8,
    reviewCount: 270,
    description: "A luxurious designer handbag crafted with premium materials.",
    price: "$350.00",
    features: [
      "Premium leather",
      "Spacious interior",
      "Elegant design",
    ],
    details: [
      { label: "Color", value: "Black" },
      { label: "Material", value: "Genuine Leather" },
    ],
    variants: [],
    longDescription: "Designer Handbag is a statement accessory that combines style with functionality and premium quality.",
  },
  {
    title: "Classic Leather Jacket",
    category: "Fashion",
    image: "https://via.placeholder.com/800x600?text=Classic+Leather+Jacket",
    rating: 4.7,
    reviewCount: 230,
    description: "A timeless leather jacket that adds edge to any outfit.",
    price: "$400.00",
    features: [
      "Genuine leather",
      "Timeless style",
      "Durable",
    ],
    details: [
      { label: "Size", value: "M-L" },
      { label: "Color", value: "Brown" },
    ],
    variants: [],
    longDescription: "Classic Leather Jacket is a versatile piece that pairs well with casual and formal looks, offering durability and style.",
  },
  {
    title: "Trendy Sneakers",
    category: "Fashion",
    image: "https://via.placeholder.com/800x600?text=Trendy+Sneakers",
    rating: 4.5,
    reviewCount: 250,
    description: "Stay comfortable and stylish with these trendy sneakers.",
    price: "$90.00",
    features: [
      "Comfortable cushioning",
      "Modern design",
      "Versatile style",
    ],
    details: [
      { label: "Size Range", value: "6-12" },
    ],
    variants: [],
    longDescription: "Trendy Sneakers are perfect for everyday wear, combining modern style with all-day comfort.",
  },
  {
    title: "Stylish Denim Jeans",
    category: "Fashion",
    image: "https://via.placeholder.com/800x600?text=Stylish+Denim+Jeans",
    rating: 4.4,
    reviewCount: 210,
    description: "High-quality denim jeans with a modern fit and timeless appeal.",
    price: "$70.00",
    features: [
      "Modern fit",
      "Durable denim",
      "Classic style",
    ],
    details: [
      { label: "Fit", value: "Slim" },
      { label: "Color", value: "Blue" },
    ],
    variants: [],
    longDescription: "Stylish Denim Jeans are a wardrobe essential, offering comfort and durability with a classic design.",
  },
  {
    title: "Formal Business Suit",
    category: "Fashion",
    image: "https://via.placeholder.com/800x600?text=Formal+Business+Suit",
    rating: 4.7,
    reviewCount: 180,
    description: "A sharp and professional business suit perfect for formal occasions.",
    price: "$500.00",
    features: [
      "Tailored fit",
      "Premium fabric",
      "Classic design",
    ],
    details: [
      { label: "Sizes", value: "S-XXL" },
    ],
    variants: [],
    longDescription: "Formal Business Suit exudes confidence and professionalism, making it an ideal choice for important meetings and events.",
  },
  {
    title: "Cozy Winter Sweater",
    category: "Fashion",
    image: "https://via.placeholder.com/800x600?text=Cozy+Winter+Sweater",
    rating: 4.6,
    reviewCount: 220,
    description: "Stay warm in style with this cozy and fashionable winter sweater.",
    price: "$60.00",
    features: [
      "Warm fabric",
      "Stylish design",
      "Comfortable fit",
    ],
    details: [
      { label: "Material", value: "Wool Blend" },
    ],
    variants: [],
    longDescription: "Cozy Winter Sweater is the perfect companion for chilly days, delivering both warmth and style.",
  },

  // ======================
  // --- Sports Products ---
  // ======================
  {
    title: "Performance Running Shoes",
    category: "Sports",
    image: "https://images.unsplash.com/photo-1515548213508-5be7e84946d6?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    rating: 4.4,
    reviewCount: 322,
    description: "High-performance running shoes engineered for optimal support and comfort during workouts.",
    price: "$120.00",
    features: [
      "Lightweight design",
      "Enhanced cushioning",
      "Breathable mesh upper",
      "Durable outsole",
    ],
    details: [
      { label: "Size", value: "9-12" },
      { label: "Weight", value: "250g" },
    ],
    variants: [
      { id: 301, size: "9", price: "$115.00" },
      { id: 302, size: "10", price: "$120.00" },
      { id: 303, size: "11", price: "$125.00" },
    ],
    longDescription: "Performance Running Shoes are engineered for athletes seeking maximum support and durability during both training and races.",
  },
  {
    title: "All-Terrain Hiking Boots",
    category: "Sports",
    image: "https://via.placeholder.com/800x600?text=All-Terrain+Hiking+Boots",
    rating: 4.7,
    reviewCount: 290,
    description: "Robust hiking boots built for comfort and stability on any terrain.",
    price: "$150.00",
    features: [
      "Water-resistant",
      "Traction sole",
      "Reinforced support",
    ],
    details: [
      { label: "Size Range", value: "7-12" },
    ],
    variants: [],
    longDescription: "All-Terrain Hiking Boots provide the durability and support needed for challenging hikes and outdoor adventures.",
  },
  {
    title: "Cycling Road Bike",
    category: "Sports",
    image: "https://via.placeholder.com/800x600?text=Cycling+Road+Bike",
    rating: 4.8,
    reviewCount: 340,
    description: "A lightweight, aerodynamic road bike designed for speed and performance.",
    price: "$1,200.00",
    features: [
      "Carbon frame",
      "Precision shifting",
      "Aerodynamic design",
    ],
    details: [
      { label: "Frame Material", value: "Carbon" },
      { label: "Gears", value: "22-speed" },
    ],
    variants: [],
    longDescription: "Cycling Road Bike is engineered for enthusiasts who demand both performance and speed on the open road.",
  },
  {
    title: "High-Impact Tennis Racket",
    category: "Sports",
    image: "https://via.placeholder.com/800x600?text=High-Impact+Tennis+Racket",
    rating: 4.5,
    reviewCount: 210,
    description: "Tennis racket designed to deliver power and control on the court.",
    price: "$130.00",
    features: [
      "Lightweight",
      "Enhanced grip",
      "Optimal balance",
    ],
    details: [
      { label: "Weight", value: "300g" },
    ],
    variants: [],
    longDescription: "High-Impact Tennis Racket offers a perfect blend of power and control, elevating your performance on the court.",
  },
  {
    title: "Professional Golf Clubs",
    category: "Sports",
    image: "https://via.placeholder.com/800x600?text=Professional+Golf+Clubs",
    rating: 4.6,
    reviewCount: 190,
    description: "A complete set of professional golf clubs for the serious player.",
    price: "$800.00",
    features: [
      "Precision engineered",
      "High-quality materials",
      "Enhanced performance",
    ],
    details: [
      { label: "Set Includes", value: "10 clubs" },
    ],
    variants: [],
    longDescription: "Professional Golf Clubs are designed to deliver precision and performance, ideal for golfers seeking to improve their game.",
  },
  {
    title: "Multi-Sport Fitness Tracker",
    category: "Sports",
    image: "https://via.placeholder.com/800x600?text=Multi-Sport+Fitness+Tracker",
    rating: 4.7,
    reviewCount: 280,
    description: "Track your performance across multiple sports with this versatile fitness tracker.",
    price: "$99.00",
    features: [
      "Heart rate monitor",
      "GPS tracking",
      "Multi-sport modes",
    ],
    details: [
      { label: "Battery Life", value: "7 days" },
    ],
    variants: [],
    longDescription: "Multi-Sport Fitness Tracker helps you monitor activity and performance, making it the ideal companion for athletes.",
  },

  // ====================
  // --- Books Products ---
  // ====================
  {
    title: "The Great Adventure",
    category: "Books",
    image: "https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    rating: 4.8,
    reviewCount: 89,
    description: "An epic tale of adventure, courage, and discovery set in uncharted territories.",
    price: "$19.99",
    features: [
      "Captivating narrative",
      "Rich character development",
      "Stunning imagery",
      "Award-winning author",
    ],
    details: [
      { label: "Format", value: "Hardcover" },
      { label: "Pages", value: "350" },
      { label: "Language", value: "English" },
    ],
    variants: [],
    longDescription: "Dive into 'The Great Adventure'—a novel that combines action, drama, and mystery in an immersive reading experience.",
  },
  {
    title: "Mystery of the Lost City",
    category: "Books",
    image: "https://via.placeholder.com/800x600?text=Mystery+of+the+Lost+City",
    rating: 4.5,
    reviewCount: 120,
    description: "A thrilling mystery that unravels the secrets of an ancient lost city.",
    price: "$14.99",
    features: [
      "Intriguing plot",
      "Unexpected twists",
      "Compelling characters",
    ],
    details: [
      { label: "Format", value: "Paperback" },
      { label: "Pages", value: "280" },
    ],
    variants: [],
    longDescription: "Mystery of the Lost City keeps readers on the edge with its suspenseful narrative and richly detailed setting.",
  },
  {
    title: "Historical Epic Saga",
    category: "Books",
    image: "https://via.placeholder.com/800x600?text=Historical+Epic+Saga",
    rating: 4.7,
    reviewCount: 140,
    description: "An expansive saga chronicling the rise and fall of ancient civilizations.",
    price: "$24.99",
    features: [
      "Detailed historical narrative",
      "Complex characters",
      "Engaging plot",
    ],
    details: [
      { label: "Format", value: "Hardcover" },
      { label: "Pages", value: "500" },
    ],
    variants: [],
    longDescription: "Historical Epic Saga immerses you in a richly detailed world of ancient empires and timeless conflicts.",
  },
  {
    title: "Romantic Poetry Collection",
    category: "Books",
    image: "https://via.placeholder.com/800x600?text=Romantic+Poetry+Collection",
    rating: 4.3,
    reviewCount: 95,
    description: "A soulful collection of poems celebrating love and passion.",
    price: "$12.99",
    features: [
      "Emotionally evocative",
      "Timeless expressions",
      "Beautifully written",
    ],
    details: [
      { label: "Format", value: "Paperback" },
      { label: "Pages", value: "150" },
    ],
    variants: [],
    longDescription: "Romantic Poetry Collection is a tender compilation of verses that capture the essence of love in its many forms.",
  },
  {
    title: "Science Fiction Odyssey",
    category: "Books",
    image: "https://via.placeholder.com/800x600?text=Science+Fiction+Odyssey",
    rating: 4.8,
    reviewCount: 160,
    description: "Embark on a futuristic journey through space and time in this sci-fi epic.",
    price: "$21.99",
    features: [
      "Imaginative world-building",
      "Thrilling adventure",
      "Complex characters",
    ],
    details: [
      { label: "Format", value: "Hardcover" },
      { label: "Pages", value: "420" },
    ],
    variants: [],
    longDescription: "Science Fiction Odyssey challenges the boundaries of reality with its visionary narrative and stunning visuals.",
  },
  {
    title: "Modern Business Strategies",
    category: "Books",
    image: "https://via.placeholder.com/800x600?text=Modern+Business+Strategies",
    rating: 4.5,
    reviewCount: 110,
    description: "A comprehensive guide to modern business practices and strategies for success.",
    price: "$29.99",
    features: [
      "Practical insights",
      "Expert advice",
      "Real-world case studies",
    ],
    details: [
      { label: "Format", value: "eBook" },
    ],
    variants: [],
    longDescription: "Modern Business Strategies provides actionable tips and proven methods to excel in today’s competitive market.",
  },
  {
    title: "Fantasy Realm Chronicles",
    category: "Books",
    image: "https://via.placeholder.com/800x600?text=Fantasy+Realm+Chronicles",
    rating: 4.9,
    reviewCount: 190,
    description: "Enter a magical realm of adventure, mythical creatures, and epic quests.",
    price: "$26.99",
    features: [
      "Rich fantasy world",
      "Engaging characters",
      "Epic storyline",
    ],
    details: [
      { label: "Format", value: "Paperback" },
      { label: "Pages", value: "380" },
    ],
    variants: [],
    longDescription: "Fantasy Realm Chronicles transports you to a wondrous world where magic and adventure abound on every page.",
  },
  {
    title: "Thrilling Detective Novel",
    category: "Books",
    image: "https://via.placeholder.com/800x600?text=Thrilling+Detective+Novel",
    rating: 4.6,
    reviewCount: 130,
    description: "A suspenseful detective story filled with twists and turns until the final reveal.",
    price: "$16.99",
    features: [
      "Intricate plot",
      "Engaging mystery",
      "Well-developed characters",
    ],
    details: [
      { label: "Format", value: "Paperback" },
      { label: "Pages", value: "320" },
    ],
    variants: [],
    longDescription: "Thrilling Detective Novel is a captivating mystery that keeps you guessing until the very end.",
  },

  // ====================
  // --- Toys Products ---
  // ====================
  {
    title: "Interactive Robot Toy",
    category: "Toys",
    image: "https://images.unsplash.com/photo-1580281657521-7a3e0fae22a1?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    rating: 4.3,
    reviewCount: 140,
    description: "A fun and interactive robot toy that encourages creativity and learning.",
    price: "$45.00",
    features: [
      "Voice recognition",
      "Interactive play modes",
      "Educational games",
      "Durable design",
    ],
    details: [
      { label: "Age Range", value: "5-10 years" },
      { label: "Battery Life", value: "5 hours" },
    ],
    variants: [],
    longDescription: "This interactive robot toy is designed to spark creativity and provide endless fun while encouraging learning.",
  },
  {
    title: "Building Block Set",
    category: "Toys",
    image: "https://via.placeholder.com/800x600?text=Building+Block+Set",
    rating: 4.7,
    reviewCount: 220,
    description: "A versatile set of building blocks that inspires creativity and construction play.",
    price: "$30.00",
    features: [
      "Multiple shapes",
      "Bright colors",
      "Safe material",
    ],
    details: [
      { label: "Pieces", value: "100" },
    ],
    variants: [],
    longDescription: "Building Block Set offers endless possibilities for imaginative play and construction.",
  },
  {
    title: "Remote Control Car",
    category: "Toys",
    image: "https://via.placeholder.com/800x600?text=Remote+Control+Car",
    rating: 4.5,
    reviewCount: 180,
    description: "A fast and agile remote control car for exciting outdoor play.",
    price: "$60.00",
    features: [
      "Fast speed",
      "Responsive controls",
      "Durable design",
    ],
    details: [
      { label: "Battery", value: "Rechargeable" },
    ],
    variants: [],
    longDescription: "Remote Control Car is perfect for kids and adults who enjoy speed and interactive outdoor fun.",
  },
  {
    title: "Educational Puzzle Game",
    category: "Toys",
    image: "https://via.placeholder.com/800x600?text=Educational+Puzzle+Game",
    rating: 4.6,
    reviewCount: 150,
    description: "An engaging puzzle game that enhances problem-solving skills and creativity.",
    price: "$25.00",
    features: [
      "Educational",
      "Interactive",
      "Fun for all ages",
    ],
    details: [
      { label: "Pieces", value: "50" },
    ],
    variants: [],
    longDescription: "Educational Puzzle Game challenges young minds with a fun and interactive approach to learning and problem solving.",
  },
  {
    title: "Plush Animal Toy",
    category: "Toys",
    image: "https://via.placeholder.com/800x600?text=Plush+Animal+Toy",
    rating: 4.4,
    reviewCount: 130,
    description: "A soft and cuddly plush toy that provides comfort and companionship.",
    price: "$20.00",
    features: [
      "Soft fabric",
      "Huggable",
      "Kid-friendly",
    ],
    details: [
      { label: "Size", value: "12 inches" },
    ],
    variants: [],
    longDescription: "Plush Animal Toy is designed for comfort and play, making it a beloved companion for children.",
  },
  {
    title: "Action Figure Collection",
    category: "Toys",
    image: "https://via.placeholder.com/800x600?text=Action+Figure+Collection",
    rating: 4.5,
    reviewCount: 200,
    description: "A collectible series of action figures featuring your favorite characters.",
    price: "$50.00",
    features: [
      "Highly detailed",
      "Articulated",
      "Collector's item",
    ],
    details: [
      { label: "Figures", value: "5" },
    ],
    variants: [],
    longDescription: "Action Figure Collection is a must-have for collectors and kids alike, offering detailed and poseable figures.",
  },
  {
    title: "Musical Toy Keyboard",
    category: "Toys",
    image: "https://via.placeholder.com/800x600?text=Musical+Toy+Keyboard",
    rating: 4.3,
    reviewCount: 140,
    description: "A fun toy keyboard that introduces children to the world of music.",
    price: "$35.00",
    features: [
      "Interactive sounds",
      "Colorful keys",
      "Educational",
    ],
    details: [
      { label: "Keys", value: "25" },
    ],
    variants: [],
    longDescription: "Musical Toy Keyboard encourages musical creativity and exploration in a fun and interactive way.",
  },
  {
    title: "Creative Art Kit",
    category: "Toys",
    image: "https://via.placeholder.com/800x600?text=Creative+Art+Kit",
    rating: 4.7,
    reviewCount: 170,
    description: "A comprehensive art kit with everything needed for creative projects.",
    price: "$40.00",
    features: [
      "Diverse art supplies",
      "Portable",
      "Encourages creativity",
    ],
    details: [
      { label: "Includes", value: "Paints, brushes, paper" },
    ],
    variants: [],
    longDescription: "Creative Art Kit provides all the tools necessary for young artists to explore and express their creativity.",
  },

  // ==========================
  // --- Grocery Products ---
  // ==========================
  {
    title: "Organic Extra Virgin Olive Oil",
    category: "Grocery",
    image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    rating: 4.7,
    reviewCount: 220,
    description: "Premium organic extra virgin olive oil, cold-pressed for maximum flavor and nutritional benefits.",
    price: "$18.00",
    features: [
      "Cold-pressed",
      "100% organic",
      "Rich in antioxidants",
      "Extra virgin quality",
    ],
    details: [
      { label: "Volume", value: "500ml" },
      { label: "Origin", value: "Italy" },
    ],
    variants: [],
    longDescription: "Our Organic Extra Virgin Olive Oil is ideal for cooking and dressings, offering rich flavor and health benefits.",
  },
  {
    title: "Artisanal Sourdough Bread",
    category: "Grocery",
    image: "https://via.placeholder.com/800x600?text=Artisanal+Sourdough+Bread",
    rating: 4.8,
    reviewCount: 180,
    description: "Freshly baked artisanal sourdough bread with a perfect crust and soft interior.",
    price: "$5.00",
    features: [
      "Handcrafted",
      "Natural fermentation",
      "Crispy crust",
    ],
    details: [
      { label: "Weight", value: "500g" },
    ],
    variants: [],
    longDescription: "Artisanal Sourdough Bread is baked using traditional methods for a delicious and nutritious loaf.",
  },
  {
    title: "Gourmet Dark Chocolate",
    category: "Grocery",
    image: "https://via.placeholder.com/800x600?text=Gourmet+Dark+Chocolate",
    rating: 4.9,
    reviewCount: 150,
    description: "Rich and smooth dark chocolate made from the finest cocoa beans.",
    price: "$8.00",
    features: [
      "High cocoa content",
      "Smooth texture",
      "Artisan crafted",
    ],
    details: [
      { label: "Weight", value: "100g" },
    ],
    variants: [],
    longDescription: "Gourmet Dark Chocolate offers a luxurious taste experience, crafted with premium ingredients.",
  },
  {
    title: "Fresh Organic Honey",
    category: "Grocery",
    image: "https://via.placeholder.com/800x600?text=Fresh+Organic+Honey",
    rating: 4.7,
    reviewCount: 170,
    description: "Pure organic honey harvested from sustainable beekeeping practices.",
    price: "$12.00",
    features: [
      "Organic",
      "Raw and unfiltered",
      "Rich in antioxidants",
    ],
    details: [
      { label: "Volume", value: "250ml" },
    ],
    variants: [],
    longDescription: "Fresh Organic Honey is a natural sweetener that brings delicious flavor and health benefits to your diet.",
  },
  {
    title: "Premium Roasted Coffee Beans",
    category: "Grocery",
    image: "https://via.placeholder.com/800x600?text=Premium+Roasted+Coffee+Beans",
    rating: 4.8,
    reviewCount: 200,
    description: "A bag of premium roasted coffee beans delivering a rich and bold flavor.",
    price: "$15.00",
    features: [
      "Freshly roasted",
      "Rich aroma",
      "Smooth taste",
    ],
    details: [
      { label: "Weight", value: "250g" },
    ],
    variants: [],
    longDescription: "Premium Roasted Coffee Beans provide a delightful coffee experience with every cup, carefully roasted to perfection.",
  },
  {
    title: "Organic Almond Butter",
    category: "Grocery",
    image: "https://via.placeholder.com/800x600?text=Organic+Almond+Butter",
    rating: 4.6,
    reviewCount: 160,
    description: "Creamy organic almond butter made with simple, natural ingredients.",
    price: "$10.00",
    features: [
      "Organic",
      "No additives",
      "Rich and creamy",
    ],
    details: [
      { label: "Volume", value: "250g" },
    ],
    variants: [],
    longDescription: "Organic Almond Butter is a nutritious spread perfect for snacks and recipes, loaded with healthy fats and flavor.",
  },
  {
    title: "Natural Free-Range Eggs",
    category: "Grocery",
    image: "https://via.placeholder.com/800x600?text=Natural+Free-Range+Eggs",
    rating: 4.5,
    reviewCount: 190,
    description: "A dozen natural free-range eggs from ethically raised chickens.",
    price: "$6.00",
    features: [
      "Free-range",
      "Fresh",
      "High nutritional value",
    ],
    details: [
      { label: "Count", value: "12 eggs" },
    ],
    variants: [],
    longDescription: "Natural Free-Range Eggs offer superior taste and nutrition, sourced from farms committed to ethical practices.",
  },
  {
    title: "Exotic Spices Collection",
    category: "Grocery",
    image: "https://via.placeholder.com/800x600?text=Exotic+Spices+Collection",
    rating: 4.7,
    reviewCount: 150,
    description: "A curated collection of exotic spices to elevate your culinary creations.",
    price: "$20.00",
    features: [
      "Variety of spices",
      "Authentic flavors",
      "Premium quality",
    ],
    details: [
      { label: "Varieties", value: "8 spices" },
    ],
    variants: [],
    longDescription: "Exotic Spices Collection brings an array of flavors to your kitchen, enhancing every dish with aromatic spices.",
  },

  // ======================
  // --- Health Products ---
  // ======================
  {
    title: "Multivitamin Supplements",
    category: "Health",
    image: "https://images.unsplash.com/photo-1581091215367-0f9ea7d48d42?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=80",
    rating: 4.5,
    reviewCount: 310,
    description: "Daily multivitamin supplements designed to support overall health and wellness.",
    price: "$29.99",
    features: [
      "Comprehensive nutrient blend",
      "Supports immune health",
      "Easy-to-swallow tablets",
    ],
    details: [
      { label: "Count", value: "60 tablets" },
      { label: "Brand", value: "HealthPlus" },
    ],
    variants: [],
    longDescription: "Our Multivitamin Supplements provide essential vitamins and minerals to support your daily health and wellness.",
  },
  {
    title: "Herbal Immune Booster",
    category: "Health",
    image: "https://via.placeholder.com/800x600?text=Herbal+Immune+Booster",
    rating: 4.6,
    reviewCount: 280,
    description: "A herbal supplement designed to naturally boost your immune system.",
    price: "$24.99",
    features: [
      "Herbal ingredients",
      "Supports immune function",
      "Natural formula",
    ],
    details: [
      { label: "Count", value: "60 capsules" },
    ],
    variants: [],
    longDescription: "Herbal Immune Booster combines the best natural ingredients to help enhance your body's defenses.",
  },
  {
    title: "Organic Green Tea Extract",
    category: "Health",
    image: "https://via.placeholder.com/800x600?text=Organic+Green+Tea+Extract",
    rating: 4.7,
    reviewCount: 240,
    description: "An organic green tea extract supplement rich in antioxidants and metabolism-boosting properties.",
    price: "$19.99",
    features: [
      "Organic",
      "Antioxidant-rich",
      "Boosts metabolism",
    ],
    details: [
      { label: "Count", value: "60 capsules" },
    ],
    variants: [],
    longDescription: "Organic Green Tea Extract supports a healthy metabolism and provides powerful antioxidants in every serving.",
  },
  {
    title: "Calcium & Vitamin D Chewables",
    category: "Health",
    image: "https://via.placeholder.com/800x600?text=Calcium+%26+Vitamin+D+Chewables",
    rating: 4.5,
    reviewCount: 200,
    description: "Chewable supplements combining calcium and vitamin D to support strong bones and teeth.",
    price: "$15.99",
    features: [
      "Chewable format",
      "Bone health",
      "Delicious flavor",
    ],
    details: [
      { label: "Count", value: "90 chewables" },
    ],
    variants: [],
    longDescription: "Calcium & Vitamin D Chewables are an easy and tasty way to support your bone health every day.",
  },
  {
    title: "Probiotic Digestive Formula",
    category: "Health",
    image: "https://via.placeholder.com/800x600?text=Probiotic+Digestive+Formula",
    rating: 4.6,
    reviewCount: 220,
    description: "A probiotic formula that supports healthy digestion and maintains gut flora balance.",
    price: "$27.99",
    features: [
      "Multiple probiotic strains",
      "Supports digestion",
      "Maintains gut health",
    ],
    details: [
      { label: "Count", value: "30 servings" },
    ],
    variants: [],
    longDescription: "Probiotic Digestive Formula is designed to promote a balanced gut microbiome for overall digestive wellness.",
  },
  {
    title: "Energy Boosting B12 Tablets",
    category: "Health",
    image: "https://via.placeholder.com/800x600?text=Energy+Boosting+B12+Tablets",
    rating: 4.7,
    reviewCount: 210,
    description: "Vitamin B12 tablets formulated to help boost energy levels and reduce fatigue.",
    price: "$18.99",
    features: [
      "Energy support",
      "Essential B12",
      "Easy to swallow",
    ],
    details: [
      { label: "Count", value: "100 tablets" },
    ],
    variants: [],
    longDescription: "Energy Boosting B12 Tablets provide a quick, effective boost to help maintain high energy levels throughout the day.",
  },
  {
    title: "Omega-3 Fish Oil Capsules",
    category: "Health",
    image: "https://via.placeholder.com/800x600?text=Omega-3+Fish+Oil+Capsules",
    rating: 4.8,
    reviewCount: 230,
    description: "High-quality fish oil capsules rich in Omega-3 fatty acids for heart and brain health.",
    price: "$22.99",
    features: [
      "Omega-3 rich",
      "Supports heart health",
      "Enhances brain function",
    ],
    details: [
      { label: "Count", value: "120 capsules" },
    ],
    variants: [],
    longDescription: "Omega-3 Fish Oil Capsules are an excellent supplement for maintaining cardiovascular and cognitive health.",
  },
  {
    title: "Stress Relief Magnesium",
    category: "Health",
    image: "https://via.placeholder.com/800x600?text=Stress+Relief+Magnesium",
    rating: 4.5,
    reviewCount: 190,
    description: "Magnesium supplement to help relieve stress and promote relaxation.",
    price: "$17.99",
    features: [
      "Stress relief",
      "Supports muscle relaxation",
      "Easy-to-digest",
    ],
    details: [
      { label: "Count", value: "120 tablets" },
    ],
    variants: [],
    longDescription: "Stress Relief Magnesium helps calm the mind and relax muscles, making it an excellent addition to your wellness routine.",
  },
  {
    title: "Collagen Beauty Powder",
    category: "Health",
    image: "https://via.placeholder.com/800x600?text=Collagen+Beauty+Powder",
    rating: 4.6,
    reviewCount: 200,
    description: "A beauty supplement with collagen powder to support skin elasticity and overall wellness.",
    price: "$29.99",
    features: [
      "Supports skin elasticity",
      "Easy to mix",
      "Unflavored",
    ],
    details: [
      { label: "Package", value: "200g" },
    ],
    variants: [],
    longDescription: "Collagen Beauty Powder helps rejuvenate your skin from within, promoting a youthful and radiant appearance.",
  },
  {
    title: "Natural Sleep Aid Capsules",
    category: "Health",
    image: "https://via.placeholder.com/800x600?text=Natural+Sleep+Aid+Capsules",
    rating: 4.7,
    reviewCount: 210,
    description: "A natural sleep aid formulated to promote restful sleep and relaxation.",
    price: "$19.99",
    features: [
      "Natural ingredients",
      "Non-habit forming",
      "Promotes deep sleep",
    ],
    details: [
      { label: "Count", value: "60 capsules" },
    ],
    variants: [],
    longDescription: "Natural Sleep Aid Capsules offer a gentle way to improve sleep quality without harsh chemicals.",
  },

];

// Seed function
async function seedProducts() {
  try {
    // Clear existing products
    await Product.deleteMany({});
    console.log("Cleared existing products.");

    // Insert new products
    const insertedProducts = await Product.insertMany(products);
    console.log(`Inserted ${insertedProducts.length} products.`);
  } catch (error) {
    console.error("Error seeding products:", error);
  } finally {
    // Close MongoDB connection
    await mongoose.disconnect();
    console.log("Database connection closed.");
    process.exit(0);
  }
}

// Run the seed function
seedProducts();
